changelog:
  categories:
    - title: "Novidades"
      labels: ["enhancement"]
    - title: "Correções"
      labels: ["bug"]
    - title: "Refatorações"
      labels: ["refactor"]
    - title: "Documentação"
      labels: ["documentation"]